Ios 16 enter name view
openworld-community/Datify-iOS-Core pull request #14
Opened 2023-09-13 20:55 UTC by goodrgn

IOS-16 Создал EnterNameView, сделал некоторые исправления: добавил case .text(_, alignment) в TextAlignment у DtCustomTF, в RegEmailView заменил RegularTextFieldView, а в SelectGenderView - Textfield (при выборе other) на DtCustomTF, ассеты добавил в DtImage Helper

2023-09-14 13:09 UTC, Irek87 approved these changes

2023-09-14 13:09 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/EnterNameView.swift
> +    private func nameIsValid () -> Bool {
И ещё можно добавить проверку на то, что строка не из пробелов состоит. 

В Extension стринга:
func trim() -> String {
    self.trimmingCharacters(in: CharacterSet.whitespaces)
}

и при валидации применять этот метод к строке.

2023-09-14 13:09 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegEmailView.swift
> +                    DtCustomTF(style: .email, input: $viewModel.email) {
👍🏼

2023-09-16 07:02 UTC, moraWoo approved these changes

2023-09-17 16:41 UTC, VolkovsaVSA requested changes

2023-09-17 18:58 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/EnterNameView.swift
> +    @ObservedObject var viewModel: RegEmailViewModel
Я сначала через нее хотел делать, а потом забыл убрать)

2023-09-17 19:33 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/EnterNameView.swift
> +        name.count > 1 && name.count < 16
Ограничил 1..<30 
Чтобы абзацы не вписывали верхняя граница имхо все равно должна быть, можно просто увеличить ее

2023-09-18 16:11 UTC, VolkovsaVSA approved these changes

2023-09-18 16:11 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/EnterNameView.swift
> +struct EnterNameView: View {
`RegEnterNameView` 
И поменяй `SelectGenderView` на `RegSelectGenderView`

2023-09-18 19:45 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/EnterNameView.swift
> +struct EnterNameView: View {
Done)

2023-09-18 19:45 UTC, merged