IOS-20 photo selection screen added
openworld-community/Datify-iOS-Core pull request #15
Opened 2023-09-15 09:45 UTC by Irek87

Добавлен экран выбора и добавления фото.
На экране SelectGenderView маленькие правки по отступам.

2023-09-16 07:08 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                        selection: $photoPickerViewModel.imageSelections[index],
Почему три фотки создал? Или у нас требования таки?

2023-09-16 07:08 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                .frame(width: 18, height: 18)
Слушай, я в итоге скачал крестик из фигмы, хотя такой же есть в эмодзи.

2023-09-17 16:39 UTC, VolkovsaVSA requested changes

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +    @StateObject private var photoPickerViewModel: PhotoPickerViewModel = .init()
Зачем здесь две вьюмодели? Надо в одну схлопнуть.

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +private struct MainSection: View {
Внутренние вью создаём внутренними переменными или фукнкицями - не надо их отдельно выносить, тогда и вьюмодель передавать не придётся лишний раз.

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +private struct PhotoSection: View {
Внутренние вью создаём внутренними переменными или фукнкицями - не надо их отдельно выносить, тогда и вьюмодель передавать не придётся лишний раз.

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                    colorScheme == .light ?
Все цвета у нас двойные - нет нужды отслеживать какая тема. Если цвет светлой темы и тёмной не совпадает с цветами юайкита из макета, то это вопрос к дизайнерам :)

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +            LazyHGrid(rows: [GridItem(.fixed(218))]) {
Не очень понял зачем тут град, так как там одна строка. Это же просто горизонтальный скрол с  горизонтальным стеком и всё. Ширина не должна быть фиксированной по идее, а должна быть процентом от ширины экрана, чтобы всегда было 2 плитки и часть. Чтобы было понятно, что можно скроллить направо.

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                            if let image = photoPickerViewModel.selectedImages[index] {
Перед любы прямым обращение по индексу массива лучше проверить, что индекс лежит внутри размера массива `index < array.count`, чтобы мы не упали от неожиданности :)

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +    @Environment(\.colorScheme) var colorScheme
нет необходимости

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                    .onChange(of: photoPickerViewModel.imageSelections[index]) { imageSelection in
Если есть вьюмодель, то отслеживание изменений надо делать там, а не вовью: Либо в дидсет, а лучше через .sink комбайна

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +            // Should I download "plus" image from Figma?
Ну лучше да, чтобы у нас было всё одинаково на обоих платформах

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +private struct DtPhotoPlaceholderView: View {
Внутренние вью создаём внутренними переменными или фукнкицями - не надо их отдельно выносить, тогда и вьюмодель передавать не придётся лишний раз.

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +private struct ButtonsSection: View {
Внутренние вью создаём внутренними переменными или фукнкицями - не надо их отдельно выносить, тогда и вьюмодель передавать не придётся лишний раз.

2023-09-17 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoViewModel.swift
> +    @Published private(set) var selectedImages: [Image?] = Array(repeating: nil, count: 3)
Тут не нужно два массива :) Достаточно функция которая создаёт имеет или как отдельная функция или как расширение к `PhotosPickerItem`. Есть вот [прям в доке](PhotosPickerItem) как это обрабатывать, тк там асинхронный код и возможна загрузка из Айклауда картинки, которая сгрузилась. Только естественно надо сделать через таски, а не GCD =)

2023-09-18 09:08 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +private struct MainSection: View {
Исправлено

2023-09-18 09:08 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +private struct PhotoSection: View {
Исправлено

2023-09-18 09:09 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                    colorScheme == .light ?
Вопрос решён. Нужны цвета из разных стилей: Primary & Secondary.

2023-09-18 09:10 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +    @Environment(\.colorScheme) var colorScheme
Ответ выше.

2023-09-18 09:10 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +            // Should I download "plus" image from Figma?
Done!

2023-09-18 09:15 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +private struct DtPhotoPlaceholderView: View {
Исправлено!

2023-09-18 09:17 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +private struct ButtonsSection: View {
Исправлено!

2023-09-18 09:36 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +    @StateObject private var photoPickerViewModel: PhotoPickerViewModel = .init()
Done!

2023-09-18 09:42 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                            if let image = photoPickerViewModel.selectedImages[index] {
Добавил данную проверку в функцию setImage

2023-09-18 09:46 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                            if let image = photoPickerViewModel.selectedImages[index] {
и здесь тоже исправил

2023-09-18 10:56 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                    .onChange(of: photoPickerViewModel.imageSelections[index]) { imageSelection in
Исправил. Сделал пока через дидсет. С комбайном ещё предстоит разобраться.

2023-09-18 13:48 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoViewModel.swift
> +    @Published private(set) var selectedImages: [Image?] = Array(repeating: nil, count: 3)
Здесь не совсем понял.
Я беру индекс ячейки, в которую положили PhotosPickerItem, и добавляю по этому же индексу в другой массив фото. 
Чтобы было куда добавлять фото, нужно, чтобы по этому индексу уже лежал хотя бы nil, чтобы не обращаться к несуществующей области памяти.
Ссылка скорее всего другая должна быть?

2023-09-19 06:06 UTC, VolkovsaVSA requested changes

2023-09-19 06:06 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoViewModel.swift
> +        didSet {
эта штука вроде получится не нужна с учётом предыдущих замечаний/изменений

2023-09-19 06:16 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +    @Environment(\.colorScheme) var colorScheme
Done!

2023-09-19 06:16 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                                    .frame(width: geo.size.width * 0.4, height: geo.size.width * 0.764)
Чтобы сохранить соотношение сторон ближе к макету. 
Как бы ты сделал?

2023-09-19 18:25 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoView.swift
> +                                    .frame(width: geo.size.width * 0.4, height: geo.size.width * 0.764)
Испавлено с помощью aspectRatio

2023-09-19 18:26 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoViewModel.swift
> +    @Published private(set) var selectedImages: [Image?] = Array(repeating: nil, count: 3)
Вопрос пока закрыт из-за сложности реализации.

2023-09-19 18:26 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegPhotoViewModel.swift
> +        didSet {
Вопрос пока закрыт из-за сложности реализации

2023-09-19 18:28 UTC, VolkovsaVSA approved these changes

2023-09-19 18:41 UTC, goodrgn approved these changes
Подтяни develop, там конфликты опять, SelectGenderView переименован теперь

2023-10-25 11:14 UTC, closed without merging

2023-10-25 11:15 UTC, Irek87 commented
Реализовано в другой ветке (IOS-20-...-my-version).