IOS-10 UI Location
openworld-community/Datify-iOS-Core pull request #16
Opened 2023-09-15 21:28 UTC by moraWoo

2023-09-16 15:29 UTC, goodrgn requested changes
Пока не полностью посмотрел

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Assets.xcassets/arrowLeft.imageset/arrowLeft.svg
Подтяни Develop, там есть эта стрелка с вариантом для темного режима

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/CountryModel.swift
> +    ]
.localize() на все стринги надо вроде добавить, подтяни девелоп, там Extension для String написан

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +            DtLogoView()
Вроде в .tabbar выносим лого

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +            Text(" Choose your city of residence; this will help us find people around you more accurately")
Добавь .padding(.horizontal), плохо выглядит когда прямо по границам текст

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +                .foregroundColor(.backgroundSecondary))
в develop добавили элемент DtBackButton

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +        }.padding(.horizontal)
добавь еще нижний padding, на SE плохо выглядит

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +import Combine
А где тут комбайн?

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +    private var cancellables = Set<AnyCancellable>()
same

2023-09-16 15:29 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift
> +                router.push(.registrationLocation)
Обратно вернуть стоит

2023-09-16 15:32 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift
> +                router.push(.registrationLocation)
Хорошо, подумал что наоборот

2023-09-16 15:32 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +import Combine
Publishers же

2023-09-16 15:34 UTC, moraWoo commented on Datify-iOS-Core/Assets.xcassets/arrowLeft.imageset/arrowLeft.svg
Да, конечно

2023-09-16 15:34 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +            DtLogoView()
Ок

2023-09-16 15:34 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/CountryModel.swift
> +    ]
Мы будем страны с бэка тянуть

2023-09-16 15:35 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +                .foregroundColor(.backgroundSecondary))
Добавлю

2023-09-16 15:35 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +        }.padding(.horizontal)
Хорошо

2023-09-16 15:35 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +    private var cancellables = Set<AnyCancellable>()
Не понял

2023-09-17 18:16 UTC, VolkovsaVSA requested changes

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +                    ForEach(countries.indices, id: \.self) { index in
лучше избегать индексов. Ну и модель же соответствует хэшбл, не вижу необходимости в индексах тут

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +                }.background(Color.white)
Цвет наш должен быть, помня о светлой и тёмной теме.

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +                    .aspectRatio(contentMode: .fit)
в девелопе есть объеденёный модификатор `resizableFit()`

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +            DtButton(title: "Next", style: .main) {
localize

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +    @Published var selectedCity: Country?
Зачем эти два параметра, если ниже есть LocationModel, где это всё есть?

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +        DispatchQueue.main.async { // Обновляем UI в главном потоке
используем конкуренси, а не GCD

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift.orig
Зачем ты коммитишь артефакты от решения конфликтов?

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationManager.swift
> +    func requestLocation() {
Не увидел, где происходит запрос разрешения на доступ к геолокации? Ты проверял работоспособность своего кода?

2023-09-17 18:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationManager.swift
> +protocol LocationManagerDelegate: AnyObject {
Этот вариант возврата данных через делегата, явно из примера :) Я бы лучше возвращал через клоужер, чтобы не создавать лишние связи через делегатов (явно рудимент мышления создателя примера из кита), а ещё лучше через асинхронную функцию с возвратом `Result` (мы всё-таки работаем с async/await) вместо двух функций делегата

2023-09-19 03:19 UTC, moraWoo commented on Datify-iOS-Core/Assets.xcassets/arrowLeft.imageset/arrowLeft.svg
Я back кнопку подтянул.

2023-09-19 03:29 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift
> +                router.push(.registrationLocation)
Теперь там registrationEmail

2023-09-20 04:12 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationManager.swift
> +        let locale = Locale(identifier: "en_US")
Потому что на русском выскакивает. Хотел на английском.

2023-09-20 05:09 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift.orig
Сорри=)

2023-09-20 05:36 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationManager.swift
> +        let locale = Locale(identifier: "en_US")
> Потому что на русском выскакивает. Хотел на английском. Симулятор сделал английским и убрал локаль

Ну так это же не кодом решается: переключи в настройках симулятор или в запускаемой схеме выбери всё необходимое...

2023-09-24 16:26 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +enum LabelOfButton {
Убрал

2023-09-24 16:30 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +            .onChange(of: viewModel.selectedCountry) { newCountry in
Что-то у меня не получается вынести из onChange

2023-09-24 16:30 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +struct LocationChooseButtonView: View {
Теперь обновляется

2023-09-24 16:30 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +    @State private var selectedCountryIndex: Int?
Я вообще все переписал тут все

2023-09-24 16:31 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +    @Published var selectedCity: Country?
Во вьюмодел убрал, но теперь во вью он появился(

2023-09-24 16:33 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +        DispatchQueue.main.async { // Обновляем UI в главном потоке
Где то все равно остались GCD.

2023-09-24 16:35 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationManager.swift
> +    func requestLocation() {
Да, код работает.

2023-09-24 16:36 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationManager.swift
> +protocol LocationManagerDelegate: AnyObject {
Убрал эти делегаты

2023-09-24 16:42 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +                Text("Choose your \(label.last ?? "")")
Сначала я сделал нормальный popover. Потом, переделал на navigationView, но теперь при переходе обратно обновляется геолокация. Думаю как это сделать

2023-09-24 18:00 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationViewModel.swift
> +        DispatchQueue.main.async { // Обновляем UI в главном потоке
Убрал GCD

2023-09-25 17:22 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +enum LabelOfButton {
Убрал

2023-09-25 17:23 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Registration/Location/LocationView.swift
> +                Text("Choose your \(label.last ?? "")")
Все теперь обновляется один раз

2023-09-27 15:07 UTC, VolkovsaVSA commented on Datify-iOS-Core/Info.plist
> +</plist>
эти изменения зачем вообще?

2023-09-27 15:09 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationManager.swift
> +                // TODO: Handle error
а кто это ту-ду должен сделать? =)

2023-09-27 15:11 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationManager.swift
> +                try await Task.sleep(nanoseconds: 10 * 1_000_000_000)
а здесь зачем слип?

2023-09-27 15:13 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationManager.swift
> +                print(String(localized: "Error: \(error.localizedDescription)"))
а зачем нам в консоле локализация? ))) удали )

2023-09-27 15:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +    @StateObject var viewModel: LocationViewModel
private

2023-09-27 15:16 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            locationChooseButton(label: String(localized: "City"), isCountrySelection: false)
`.localize()`

2023-09-27 16:06 UTC, moraWoo commented on Datify-iOS-Core/Helpers/AppConstants.swift
> +""")
прости, не сделал pull

2023-09-27 16:10 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationManager.swift
> +                print(String(localized: "Error: \(error.localizedDescription)"))
удалил=)

2023-09-27 16:11 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +    @StateObject var viewModel: LocationViewModel
добавил

2023-09-27 16:18 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            locationChooseButton(label: String(localized: "City"), isCountrySelection: false)
сделал

2023-09-28 03:26 UTC, moraWoo commented on Datify-iOS-Core/Info.plist
> +</plist>
Я не знаю, откуда он=)

2023-09-28 03:26 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            locationChooseButton(label: String(localized: "Country"), isCountrySelection: true)
сделал

2023-09-28 03:28 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +                    Image("iconArrowBottom")
сделал

2023-09-28 03:28 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            return location?.selectedCountry?.name ?? String(localized: "Loading...")
сделал

2023-09-28 03:30 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +                return AnyView(
сделал. А чем лучше такой подход?

2023-09-28 03:33 UTC, moraWoo commented on Datify-iOS-Core.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSLocationWhenInUseUsageDescription = "";
А зачем мы определяем геопозицию?=)

2023-09-28 03:33 UTC, moraWoo commented on Datify-iOS-Core.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSLocationWhenInUseUsageDescription = "";
Ну что-то написал

2023-09-28 03:34 UTC, moraWoo commented on Datify-iOS-Core.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_NSLocationWhenInUseUsageDescription = "";
Может merge? Не знаю

2023-09-28 03:35 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +                    .navigationBarTitle(String(localized: "Choose your \(label)"))
сделал

2023-09-28 03:36 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            Text(String(localized: "Where are you located?"))
сделал

2023-09-28 03:36 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            DtButton( title: String(localized: "Next"), style: .main) {
сделал

2023-09-28 03:37 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +//            .hideKeyboardTapOutside()
не смог сделать pull -> проект не собирался -> закомментил (забыл откомментить)

2023-09-28 03:38 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            return location?.selectedCountry?.selectedCity ?? String(localized: "Loading...")
сделал

2023-09-28 03:39 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationManager.swift
> +                // TODO: Handle error
ну я буду делать, как общие алерты появятся. Или как мы будем показывать ошибки?

2023-09-28 03:51 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationManager.swift
> +                // TODO: Handle error
Я пока свой алерт добавил. Или мы так и будем делать?

2023-09-28 03:56 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationManager.swift
> +                try await Task.sleep(nanoseconds: 10 * 1_000_000_000)
Если программа сразу не определит геолокацию, то через 10 сек еще раз попытается.

2023-09-28 03:57 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationManager.swift
> +                try await Task.sleep(nanoseconds: 10 * 1_000_000_000)
Скажи, я поменяю, но нам все равно нужен хэндл для обработки ошибок. Правда пока не знаю каких

2023-09-28 04:00 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            // TODO: when screen has appeared
Вроде написал.

2023-09-28 04:06 UTC, moraWoo commented on Datify-iOS-Core/Info.plist
> +</plist>
удалил

2023-10-06 16:23 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            destination: locationList,
я вроде сделал

2023-10-08 16:26 UTC, VolkovsaVSA requested changes

2023-10-08 16:26 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/CountryAndCityView.swift
> +    @ObservedObject var viewModel: LocationViewModel
`private`, тк передаёшь через инит.

2023-10-08 16:26 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/CountryAndCityView.swift
> +    var isCountrySelection: Bool
`private`, тк передаёшь через инит.

2023-10-08 16:26 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/CountryAndCityView.swift
> +    private func selectLocation(_ location: String) {
не вижу, где используется эта функция

2023-10-08 16:26 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +        .onAppear {
если у тебя` .onAppear { `и внутри есть таск, то проще использовать` .task { ... }` вместо `.onAppear`

2023-10-08 16:26 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +        .onReceive(viewModel.$error) { error in
эта обработка должна быть внутри вьюмодели

2023-10-08 16:26 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +                    .textInputAutocapitalization(.sentences)
зачем вьюшке `Text` модификатор `.textInputAutocapitalization(.sentences)`, который используется для ввода текста?

2023-10-08 16:26 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            Text("Where are you located?".localize())
внутри штатных вьюг не надо `.localize()`

2023-10-08 16:26 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            Text("Choose your city of residence, this will help us find people around you more accurately".localize())
внутри штатных вьюг не надо` .localize()`

2023-10-08 17:01 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/CountryAndCityView.swift
> +    @ObservedObject var viewModel: LocationViewModel
Готово

2023-10-08 17:03 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/CountryAndCityView.swift
> +    var isCountrySelection: Bool
Готово

2023-10-08 17:04 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/CountryAndCityView.swift
> +    private func selectLocation(_ location: String) {
Готово

2023-10-08 17:08 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +        .onAppear {
Готово

2023-10-08 17:17 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +                    .textInputAutocapitalization(.sentences)
Удалил

2023-10-08 17:28 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            Text("Where are you located?".localize())
Я конечно удалил, но они же будут меняться?

2023-10-08 17:28 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            Text("Choose your city of residence, this will help us find people around you more accurately".localize())
Я конечно удалил, но они же будут меняться?

2023-10-08 18:00 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +        .onReceive(viewModel.$error) { error in
Вроде сделал

2023-10-08 18:30 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            Text("Where are you located?".localize())
да

2023-10-08 18:30 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Location/LocationView.swift
> +            Text("Choose your city of residence, this will help us find people around you more accurately".localize())
да

2023-10-08 18:30 UTC, VolkovsaVSA approved these changes

2023-10-09 06:45 UTC, Irek87 approved these changes

2023-10-09 11:32 UTC, goodrgn approved these changes

2023-10-12 03:17 UTC, merged