Ios 17 date of birth view
openworld-community/Datify-iOS-Core pull request #17
Opened 2023-09-18 20:04 UTC by goodrgn

IOS-17 DateOfBirthView, сделал вьюху, кастомный пикер даты вроде подогнал по цветам под макет, выбрать дату можно только чтоб возраст был 16+ (изменяется параметром minimumAge в DtCustomDatePicker), в SelectGenderView добавил исправление ввода кастомного гендера (отсечение пробелов повторяющихся и в начале и в конце)

2023-09-21 16:14 UTC, VolkovsaVSA requested changes

2023-09-21 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtCustomDatePicker.swift
> +            updateSelectedDate()
тоже код, что и в строках 111-114. Можно вынести в функцию

2023-09-21 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtCustomPicker.swift
> +    var content: (Item) -> Content
let

2023-09-21 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtCustomPicker.swift
> +    var items: [Item]
let

2023-09-21 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtCustomDatePicker.swift
> +    @State private var selectedYear = 1990
Мне кажется выбранные данные надо выставлять в ините как раз в максимальные значения в зависимости от минимального возраста. 
От текущей даты (от годов) отнимешь минимальный возраст вот и готовый выбранный день, месяц, год

2023-09-21 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegBirthdayView.swift
> +        dateComponents.year = 1990
Мне кажется, выбранные данные надо выставлять в ините как раз в максимальные значения в зависимости от минимального возраста.

2023-10-12 13:03 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtCustomPicker.swift
> +    var content: (Item) -> Content
done

2023-10-12 13:05 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtCustomDatePicker.swift
> +        return newArray
Да, ты прав, исправил)

2023-10-12 13:07 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtCustomDatePicker.swift
> +    private let months = ["January".localize(), "February".localize(),
Я сначала через массив делал, потом заменил на энум, забыл убрать, удалил)

2023-10-12 13:10 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtCustomDatePicker.swift
> +            DtCustomPicker(selectedItem: $selectedMonth, items: selectedMonth.arrayOfIndices(maxMonth: maxMonthForCurrentYear)) { month in
Не отключал, но почему-то не выдавал ошибку либо я проглядел, сейчас вижу, исправил

2023-10-15 15:05 UTC, VolkovsaVSA approved these changes

2023-10-16 19:48 UTC, moraWoo approved these changes

2023-10-16 19:49 UTC, merged