IOS-18 RegOccupationView
openworld-community/Datify-iOS-Core pull request #19
Opened 2023-09-19 18:30 UTC by goodrgn

2023-09-21 16:21 UTC, VolkovsaVSA requested changes

2023-09-21 16:21 UTC, VolkovsaVSA commented on Datify-iOS-Core/Assets.xcassets/selectedCircle.imageset/Contents.json
> +      "filename" : "selectedCircle.svg",
ну это же не иконка. Надо сделать через код Circle, чтобы элемент был масштабиуемый.

2023-09-21 16:21 UTC, VolkovsaVSA commented on Datify-iOS-Core/Assets.xcassets/unselectedCircle.imageset/Contents.json
> +      "filename" : "unselectedCircleLight.svg",
ну это же не иконка. Надо сделать через код  Circle и stroke, чтобы элемент был масштабиуемый.

2023-09-21 16:21 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtSelectorButton.swift
> +            withAnimation {action()}
пробельчики ))) `{ action() }`

2023-09-22 09:06 UTC, Irek87 approved these changes

2023-09-22 09:06 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegOccupationView.swift
> +extension RegOccupationView {
private extension - возможно так лучше

2023-10-09 11:46 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtSelectorButton.swift
> +            withAnimation {action()}
done)

2023-10-09 11:48 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegOccupationView.swift
> +extension RegOccupationView {
done

2023-10-09 17:12 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Welcome/Registration/RegOccupationView.swift
> +        .padding(.bottom, 8)
А сколько мы ставим? Я в RegEmailView подсмотрел

2023-10-09 17:13 UTC, goodrgn commented on Datify-iOS-Core/Assets.xcassets/selectedCircle.imageset/Contents.json
> +      "filename" : "selectedCircle.svg",
Исправил)

2023-10-09 17:13 UTC, goodrgn commented on Datify-iOS-Core/Assets.xcassets/unselectedCircle.imageset/Contents.json
> +      "filename" : "unselectedCircleLight.svg",
Исправил)

2023-10-11 15:35 UTC, merged