Ios 29 UI tabbar
openworld-community/Datify-iOS-Core pull request #22
Opened 2023-10-08 13:20 UTC by moraWoo

2023-10-11 16:14 UTC, VolkovsaVSA requested changes

2023-10-11 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/TabItem.swift
> +//    static let tabbarIds: Locators.TapBarTags = .init()
закомменченный код удалить ))

2023-10-11 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +struct TrTabbar<Content: View>: View {
Контору палишь названием ))) Сделай наше =)

2023-10-11 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/TabbarView.swift
> +            DatingView(router: viewModel.router)
из вьюбилдера надо брать вьюшки )

2023-10-11 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +    @Environment(\.colorScheme) var colorScheme
а где используется?  ))

2023-10-11 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +                                    badgeCount: 0
наверное отправлять вовнутрь этот параметр не стоит, тк у нас только чат вроде бейж предполагает. Сделай как в "примере", что если выбран конкретный кейс таба, то мы накладываем бейдж. А его уж возмём из модели

2023-10-11 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +//                    .frame(height: 72)
удалить

2023-10-11 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +    @Environment(\.colorScheme) var colorScheme
а где используется? ))

2023-10-11 16:14 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginViewModel.swift
> +import SwiftUI
а надо?

2023-10-11 16:20 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginViewModel.swift
> +import SwiftUI
сделал

2023-10-11 16:20 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +    @Environment(\.colorScheme) var colorScheme
убрал

2023-10-11 16:20 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +//                    .frame(height: 72)
удалил

2023-10-11 16:21 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +struct TrTabbar<Content: View>: View {
переименовал

2023-10-11 17:39 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Tabbar/TabbarView.swift
> +            DatingView(router: viewModel.router)
сделал

2023-10-11 17:39 UTC, moraWoo commented on Datify-iOS-Core/NavigationStack/NavigationViewBuilder/MainFlow.swift
> +        DatingView(router: router)
сделал

2023-10-11 17:39 UTC, moraWoo commented on Datify-iOS-Core/NavigationStack/AppRoute.swift
> +    case dating
убрал

2023-10-12 03:21 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Tabbar/TrTabbar.swift
> +                                    badgeCount: 0
сделал

2023-10-15 14:42 UTC, VolkovsaVSA requested changes

2023-10-15 14:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/MainAppView.swift
> +        case .tabbar: navViewBuilder.createTabbarView(viewBuilder: navViewBuilder)
Зачем передавать в функцию вьюбилдера себя самого???

2023-10-15 14:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/NavigationStack/NavigationViewBuilder/LoginFlow.swift
> +    func createTabbarView(viewBuilder: NavigationViewBuilder) -> some View {
Зачем передавать в функцию вьюбилдера себя самого???

2023-10-15 15:03 UTC, moraWoo commented on Datify-iOS-Core/MainAppView.swift
> +        case .tabbar: navViewBuilder.createTabbarView(viewBuilder: navViewBuilder)
сделал

2023-10-15 15:03 UTC, moraWoo commented on Datify-iOS-Core/NavigationStack/NavigationViewBuilder/LoginFlow.swift
> +    func createTabbarView(viewBuilder: NavigationViewBuilder) -> some View {
сделал

2023-10-15 15:06 UTC, VolkovsaVSA approved these changes

2023-10-15 15:08 UTC, moraWoo commented on Datify-iOS-Core/NavigationStack/NavigationViewBuilder/LoginFlow.swift
> +    func createTabbarView(viewBuilder: NavigationViewBuilder) -> Tabbar
перенес

2023-10-15 17:13 UTC, Irek87 approved these changes

2023-10-15 17:14 UTC, merged