Ios 24 dating filter view
openworld-community/Datify-iOS-Core pull request #24
Opened 2023-10-18 18:06 UTC by goodrgn

IOS-24 commit, сделал фильтр вью (Без локации, пока не отрисовано как должно выглядеть), при нажатии Apply changes изменения сохраняются в UserDefaults (возможно потом будем отправлять на бэк / подтягивать с бэка или CoreData / SwiftData), при скрытии Sheet через XMarkButton изменения не сохраняются. Добавил в DatingView кнопку которой можно вызвать DatingFilterView в виде Sheet, при появлении которого DatingView блюрится

2023-10-22 18:24 UTC, VolkovsaVSA requested changes

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +            let step = geometry.size.width/4
здесь всё-таки надо принимать на вход какую-то модель, от которой и количество степов будет браться и текст на лейблы. Какой-то энум видимо =)

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +    private var labelStack: some View {
здесь всё-таки надо принимать на вход какую-то модель, от которой и количество степов будет браться и текст на лейблы. Какой-то энум видимо =)

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +                Text(label2)
ForEach же лучше, чем копипаста =)

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +                switch selectedDistance {
нужно делать зависимость/функцию от размера вью, а не конкретные значения

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtXMarkButton.swift
> +    private let dismiss: DismissAction?
Зачем снаружи передавать дисмисс, я не понял. Ты можешь просто вызывать даже "местный" дисмисс и будет всё ок 
`@Environment(\.dismiss) private var dismiss` а перед dismiss() вызывать экшен

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtXMarkButton.swift
> +            Task {
просто

```
action()
dismiss()
```

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilterView.swift
> +    @StateObject var viewModel: DatingFilterViewModel
private

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilterView.swift
> +    @Environment(\.dismiss) var dismiss
private

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/TabItem.swift
> +// import shared
удалить закоменченное

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/FilterModel.swift
> +//        self.location = updatedFilter.location
удалить закоменченное

2023-10-22 18:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/FilterModel.swift
> +//    private(set) var location: LocationModel
удалить закоменченное

2023-10-22 18:36 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +                    try? await Task.sleep(nanoseconds: UInt64(30))
Там короче когда шит активируется баг есть что сначала geometry reader очень маленькую ширину читает и все ломается из-за этого

2023-10-23 13:44 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +                switch selectedDistance {
Оно зависит от размера вью, step передается из geometry reader, конкретные цифры в оффсете - чтобы кружок выбора по центру пунктов был, то есть вычитается половина его ширины, а на крайних чуть меньше/чуть больше чтоб за рамки далеко кружок не выходил, плохо смотрится. Могу сделать чтоб размер кружка передавался извне

2023-10-23 13:49 UTC, goodrgn commented on Datify-iOS-Core/Assets.xcassets/strokes.imageset/Strokes.svg
Тут не понял, это же из макета, которая на кнопке слайдера

2023-10-23 13:50 UTC, goodrgn commented on Datify-iOS-Core/Assets.xcassets/checkMark.imageset/Frame 2043682382.svg
Заменил

2023-10-23 13:51 UTC, goodrgn commented on Datify-iOS-Core/Helpers/DtImage.swift
> +    static let checkmark = "checkmark"
Изменил

2023-10-23 15:04 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilterView.swift
> +    @Environment(\.dismiss) var dismiss
done

2023-10-23 15:04 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +    @Environment(\.colorScheme) var colorScheme
done

2023-10-23 15:04 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +    @State var offset: CGFloat = -6
done

2023-10-23 22:22 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtXMarkButton.swift
> +    private let dismiss: DismissAction?
Сделал

2023-10-23 22:22 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtXMarkButton.swift
> +            Task {
Сделал

2023-10-23 22:23 UTC, goodrgn commented on Datify-iOS-Core.xcodeproj/project.pbxproj
> +				20FD2D302ADDCEAA0051C894 /* DatingFilterView.swift */,
Done

2023-10-25 12:42 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +            let step = geometry.size.width/4
Переделал чтоб слайдер адаптировался под входные параметры

2023-10-25 12:42 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +    private var labelStack: some View {
Переделал чтоб слайдер адаптировался под входные параметры

2023-10-26 08:19 UTC, Irek87 approved these changes

2023-10-26 08:35 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +                    try? await Task.sleep(nanoseconds: UInt64(30))
У меня тоже была схожая проблема. Geometry Reader выдавал 0. Поэтому я внёс как расширение такой модификатор

2023-10-26 08:36 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtDistanceSlider.swift
> +                    try? await Task.sleep(nanoseconds: UInt64(30))
У меня тоже была схожая проблема. Geometry Reader выдавал 0. Поэтому я внёс как расширение такой модификатор
https://github.com/openworld-community/Datify-iOS-Core/pull/25/files#diff-3be06ce6bd1f5425eb38fe21f510e7cf5f5763f3966050cd6cff6d097e7c8d9e:~:text=func-,readSize,-(onChange%3A

Применение тут
https://github.com/openworld-community/Datify-iOS-Core/pull/25/files#diff-72320459cafb8ff4888ca7ba1ab490c7c6903f2dfc3e858c2113da364470668d:~:text=.-,readSize,-(onChange%3A%20%7B%20newSize

2023-10-26 10:19 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilter/DatingFilterView.swift
> +                Text(item.title()).tag(item)
Модификатор .tag() применяешь дважды, тут и к context в DtSegmentedPicer()

2023-10-26 10:58 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilter/DatingFilterView.swift
> +                    Text("\(age)").tag(age)
Модификатор .tag() применяешь дважды, тут и к content в DtCustomPicker()

2023-10-26 10:58 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilter/DatingFilterView.swift
> +                    Text("\(age)").tag(age)
Модификатор .tag() применяешь дважды, тут и к content в DtCustomPicker()

2023-10-26 11:05 UTC, baranov89 commented on Datify-iOS-Core/Views/Common/DtStepSliderSegment.swift
> +         offset: CGFloat = 0,
не нашел где используется offset

2023-10-26 11:32 UTC, baranov89 approved these changes

2023-10-26 16:25 UTC, VolkovsaVSA commented on Datify-iOS-Core/Assets.xcassets/strokes.imageset/Strokes.svg
это иконка вызова твоего вью или другая, которая внутри вью? :)

2023-10-26 16:37 UTC, goodrgn commented on Datify-iOS-Core/Assets.xcassets/strokes.imageset/Strokes.svg
Которая в слайдере,  вызова вью системная временно
<img width="57" alt="Снимок экрана 2023-10-26 в 19 37 10" src="https://github.com/openworld-community/Datify-iOS-Core/assets/139252973/3755e801-6809-460d-bde4-50b36cbeb6e6">

2023-10-26 16:47 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtStepSliderSegment.swift
> +         offset: CGFloat = 0,
Убрал, действительно уже не используется)

2023-10-26 16:47 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilter/DatingFilterView.swift
> +                    Text("\(age)").tag(age)
Ты прав, пофиксил

2023-10-26 16:48 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilter/DatingFilterView.swift
> +                    Text("\(age)").tag(age)
Ты прав, пофиксил

2023-10-26 16:48 UTC, goodrgn commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/DatingFilter/DatingFilterView.swift
> +                Text(item.title()).tag(item)
Ты прав, пофиксил

2023-10-26 16:48 UTC, goodrgn commented on Datify-iOS-Core/Views/Common/DtStepSlider.swift
> +    private func getColorSchemeMask() -> some View {
Хорошо, исправил)

2023-11-07 14:08 UTC, VolkovsaVSA approved these changes

2023-11-07 18:23 UTC, merged