Ios 11 UI voice recordig view new
openworld-community/Datify-iOS-Core pull request #27
Opened 2023-11-12 15:34 UTC by baranov89

2023-11-12 16:51 UTC, Irek87 requested changes
Конфликтует с веткой 'develop'. Возможно, лучше сразу develop замерджить в свою.

2023-11-15 08:21 UTC, Irek87 requested changes

2023-11-15 08:21 UTC, Irek87 commented on Datify-iOS-Core/Helpers/DtImage.swift
> +    static let delete = "delete"
В Assets названия изображений с большой буквы. Это не вызывает ошибку? У меня  XCode ругается.

2023-11-15 08:21 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordView.swift
> +        NavigationStack {
Тут нужен NavigationStack? 🤔

2023-11-15 08:21 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordView.swift
> +struct RegRecordView: View {
В этом файле не хватает `.navigationBarBackButtonHidden`

2023-11-15 08:21 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordView.swift
> +        NavigationStack {
Из-за этого ломается на симуляторе

2023-11-15 08:28 UTC, Irek87 commented on Datify-iOS-Core/Helpers/DtImage.swift
> +    static let delete = "delete"
И картинки не отображаются на экране

2023-11-15 08:28 UTC, Irek87 commented
Вышло красиво 👍🏼

2023-11-15 10:18 UTC, baranov89 commented on Datify-iOS-Core/Helpers/DtImage.swift
> +    static let delete = "delete"
Странно, у меня с маленькой буквы названия в Assets

2023-11-15 10:36 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    private func isFileExists(audioURL: URL) {
Поправил

2023-11-15 10:38 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphView.swift
> +extension VoiceGraphView {
Поправил

2023-11-15 10:43 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordViewModel.swift
> +        guard let url = URL(string: UIApplication.openSettingsURLString),
Поправил

2023-11-15 10:43 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordView.swift
> +        NavigationStack {
NavigationStack лишний, удалил

2023-11-15 10:43 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordView.swift
> +struct RegRecordView: View {
Добавил

2023-11-15 10:46 UTC, baranov89 commented on Datify-iOS-Core/Views/Common/DtCircleButton.swift
> +        } label: {
Поправил

2023-11-15 10:46 UTC, baranov89 commented on Datify-iOS-Core/Views/Common/DtCircleButton.swift
> +import Foundation
Удалил

2023-11-16 21:08 UTC, Irek87 approved these changes

2023-11-18 13:48 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    @Published var wightVoiceGraph: CGFloat = 0
)))) ширина видимо

2023-11-18 16:56 UTC, VolkovsaVSA requested changes

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    var isAuthorized: Bool {
```
func isAuthorized() async -> Bool {
        let status = AVCaptureDevice.authorizationStatus(for: .audio)
        var isAuthorized = status == .authorized
        if status == .notDetermined {
            isAuthorized = await AVCaptureDevice.requestAccess(for: .audio)
        }
        return isAuthorized
    }
```

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordViewModel.swift
> +              UIApplication.shared.canOpenURL(url) else { return }
DI

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordViewModel.swift
> +    func checkRecordAuthStatus() {
сделать обработку пермишенов в одном менеджере

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphView.swift
> +    @StateObject var viewModel: VoiceGraphViewModel
private

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphView.swift
> +            .animation(.none, value: viewModel.statePlayer)
?

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtCircleButton.swift
> +                    .animation(nil, value: UUID())
.animation(nil, value: 0)

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +        return (!fileExists || statePlayer != .inaction) ? true : false
(!fileExists || statePlayer != .inaction) ? true : false

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +        return (statePlayer == .play ||
return  можно не писать

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +        return (!fileExists || statePlayer == .record) ? true: false
return можно не писать

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +            if let filePath = filePath {
`if let filePath  {`

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +        case .inaction, .pause:
не inAction, а .idle

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    private func isFileExists(audioURL: URL) {
doFileExists

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    func didTapRecordButton() {
```
@MainActor
func didTapRecordButton() async
```

и лишняя таска уйдёт

2023-11-18 16:56 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +            if fileExists {
чтобы каждый раз не проверять, можно пихать в клоужер 

`func isFileExists(audioURL: URL, callBack: (() -> Void)? = nil) `

2023-11-19 11:32 UTC, baranov89 commented on Datify-iOS-Core/Helpers/AppConstants.swift
> +        static let recordVoice: String = "recordVoice"
исправил

2023-11-19 11:38 UTC, baranov89 commented on Datify-iOS-Core/Views/Common/DtCircleButton.swift
> +        case big = 96
исправил

2023-11-19 11:38 UTC, baranov89 commented on Datify-iOS-Core/Views/Common/DtCircleButton.swift
> +                    .frame(width: style.rawValue/2, height: style.rawValue/2)
перенес

2023-11-19 11:55 UTC, baranov89 commented on Datify-iOS-Core/Views/Common/DtCircleButton.swift
> +                    .animation(nil, value: UUID())
удалил вообще

2023-11-19 11:56 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +    private enum Constant {
вынес

2023-11-19 12:13 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +            AVEncoderAudioQualityKey: AVAudioQuality.high.rawValue
441000 (стандартный для CD качества звука) - вес 200KB
48000 (стандартный для профессионального аудио) - вес 250KB
это при 2 каналах, если канал 1 то но 100KB меньше, 
оставил 48000 и 2 канала

2023-11-19 12:15 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphView.swift
> +            .animation(.none, value: viewModel.statePlayer)
удалил

2023-11-19 12:15 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    @Published var wightVoiceGraph: CGFloat = 0
поправил

2023-11-19 12:15 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +    private enum Constant {
вынес

2023-11-19 12:16 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +        statePlayer = .inaction
поменял на idle

2023-11-19 12:26 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +            audioPlayer?.play()
поправил

2023-11-19 12:26 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +        if let audioPlayer = audioPlayer {
удалил

2023-11-19 12:26 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +        self.timer = Timer.scheduledTimer(withTimeInterval: timerFrequency, repeats: true, block: { [weak self] _ in
поправил

2023-11-19 12:28 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +            guard let self = self else { return }
поправил

2023-11-19 12:39 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +                self.heightsBar[self.index].height = Float(self.minHeightBar)
добавил проверку

2023-11-19 12:45 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +        if !powerValues.isEmpty {
добавил

2023-11-19 12:50 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +                heightsBar.append(BarModel(height: Float(resultArray[index]), coloredBool: true))
убрал индекс

2023-11-19 13:01 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +            heightsBar[index].coloredBool = true
оставил индекс, тк не могу менять item внутри for тк он let

2023-11-19 15:23 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +            guard let self = self else { return }
поправил

2023-11-19 15:23 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +            guard let self = self else { return }
поправил

2023-11-19 15:26 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +            if self.index <= heightsBar.count - 1 {
поправил

2023-11-19 17:24 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +            if !canStopRecord {
поправил

2023-11-19 17:24 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +                    guard let self = self else { return }
поправил

2023-11-19 17:24 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +                    if index <= (heightsBar.count) - 1 {
поправил

2023-11-19 17:25 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +                })
удалил

2023-11-19 17:29 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordView.swift
> +                Button("Cancel", role: .cancel, action: {viewModel.isAlertShowing = false})
поправил

2023-11-19 17:31 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordView.swift
> +            .disabled(!viewModel.fileExistsBool)
поправил

2023-11-19 17:31 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordViewModel.swift
> +    @Published var fileExistsBool: Bool = false
поправил

2023-11-19 17:31 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordViewModel.swift
> +              UIApplication.shared.canOpenURL(url) else { return }
поправил

2023-11-19 18:20 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RegRecordViewModel.swift
> +    func checkRecordAuthStatus() {
добавил PermissionCenter

2023-11-19 18:21 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphView.swift
> +    @StateObject var viewModel: VoiceGraphViewModel
поправил

2023-11-19 18:34 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    var isAuthorized: Bool {
изменил

2023-11-19 18:37 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    private func isFileExists(audioURL: URL) {
исправил

2023-11-19 18:49 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +        return (!fileExists || statePlayer != .inaction) ? true : false
поправил

2023-11-19 18:49 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +        return (statePlayer == .play ||
поправил

2023-11-19 18:49 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +        return (!fileExists || statePlayer == .record) ? true: false
поправил

2023-11-19 18:52 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +        case .inaction, .pause:
поправил

2023-11-19 18:53 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +            if let filePath = filePath {
поправил

2023-11-19 18:55 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +    func didTapRecordButton() {
поправил

2023-11-19 19:08 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/VoiceGraphViewModel.swift
> +            if fileExists {
поправил

2023-12-04 09:09 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Welcome/RecordVoice/RecordManager.swift
> +    private var maxHeightBar: CGFloat = 0
проверил

2023-12-04 11:09 UTC, merged