IOS-107 blocking complaint
openworld-community/Datify-iOS-Core pull request #33
Opened 2023-12-05 13:25 UTC by Irek87

Пока без мерджа последних обновлений в develop.

2023-12-10 17:55 UTC, VolkovsaVSA requested changes

2023-12-10 17:55 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +        case fake = "Fake"
Тайтл вынести в метод или вычисляемую переменную, тк текст надо локализовать

2023-12-10 17:55 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ConfirmationView.swift
> +                VStack(spacing: 32) {
такой же код, что и в предыдущем кейс. Надо или функцию или переменную

2023-12-10 17:55 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +        var complainDetails: [String] {
не очень понял, зачем тут массив. В любом случае забыл `.localize()` тип измени на `LocalizedStringKey` и будет всё ок =)

2023-12-11 10:06 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +        case fake = "Fake"
Done!

2023-12-11 10:20 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ConfirmationView.swift
> +                VStack(spacing: 32) {
Done!

2023-12-11 12:40 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +        var complainDetails: [String] {
> не очень понял, зачем тут массив

У каждой категории жалобы есть будут подкатегории. Если нужно/возможно сделать по-другому, подскажи?

> тип измени на LocalizedStringKey и будет всё ок =)

получаю ошибку в ForEach, что `LocalizedStringKey` не соответствует `Hashable`. Стоит ли расширять `LocalizedStringKey` под `Hashable` или можно просто оставить с добавлением `.localize()` к каждой String?

2023-12-11 15:22 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +        var complainDetails: [String] {
Проще тогда модель нормальную создать жалобы, чем курсы засовывать в дескрипшен... типа такой или как там удобнее

```
protocol ComplaintAddInfoProtocol {}
enum Complaint {
    case fake, spam
    
    enum Fake: ComplaintAddInfoProtocol {
        case one, two
    }
    enum Spam: ComplaintAddInfoProtocol {
        case one, two
    }
}

struct ComplaintModel {
    let complaintType: Complaint
    let adInfo: [ComplaintAddInfoProtocol]
}
```

2023-12-11 22:16 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +        var complainDetails: [String] {
Ещё больше запутало.
Создал `ComplaintModel`. В ForEach в итоге попадает массив `adInfo: [ComplaintAddInfoProtocol]`. 
Требуется имплементация Hashable и тут начинаются проблемы.
Или я неправильно всё понял?

2023-12-12 12:20 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ConfirmationView.swift
> +    private func getDescription(for type: ConfirmationType) -> some View {
Параметр функции не используется

2023-12-12 12:24 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/BlockView.swift
> +                        onCancel()
если поменять на  
```
DtButton(title: "No, cancel", 
                             style: .picker) {
                        onCancel()
                    }
```
вроде то же самое получается

2023-12-12 13:07 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +                if !textFieldIsFocused {
Вкусовщина - мне кажется отслеживание фокуса не очень подходит т.к. при появлении TextField  кнопка "Send a complaint" доступна хотя текст еще не введен, + при скрытии клавиатуры, TextField спускается вниз а кнопка неподвижна сразу внизу - выглядит не очень, Может отслеживать пустой ли complainText? и дизейблить кнопку?
  ```
 DtButton(title: "Send a complaint", style: .main) {
                        // TODO: action
                        Task { @MainActor in
                            isPresented = false
                            onCompleted()
                        }
                    }
                    .disabled(complainText == "")
``` а может и фокус и текст отслеживать сразу ...

2023-12-12 15:17 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +            .hideKeyboardTapOutside()
Функция возвращает  onTapGesture { UIApplication.shared.dismissKeyboard() }, тоесть если тапнуть на View на котором вызвана функция - должна закрыться клавиатура, в данном случае функция применяется к VStack в котором только TextField (кнопка в этот момент скрыта) получается высота VStack равна TextField - в итоге чтобы закрыть клавиатуру нужно тапнуть на TextField, хотя инстинктивно чтобы закрыть клаву хочется тапнуть в любое другое место но не в TextField ))

2023-12-12 15:24 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +        var complainDetails: [String] {
ну у тебя первый Фомич - это `[ComplaintModel]`, это раньше у тебя было ComplainCases.allCases, а потом второй форич - это уже `adInfo: [ComplaintAddInfoProtocol]`.
Ну если надо соответствие хэшбел так добавь )) Энумам вроде даже ничего оне надо добавлять для реализации этого протокола 
Если надо, то добавляешь реализацию хэша
```
func hash(into hasher: inout Hasher) {
    hasher.combine(self)
}
```

2023-12-12 15:30 UTC, baranov89 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +            .hideKeyboardTapOutside()
отбой, все норм, там места та свободного совсем нет, только TextField )))

2023-12-14 16:25 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +        var complainDetails: [String] {
Принял. Сделал. `func hash` не понадбилась.

2023-12-14 16:31 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/BlockView.swift
> +                        onCancel()
Да, спасибо! Поменял.

2023-12-14 16:36 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ConfirmationView.swift
> +    private func getDescription(for type: ConfirmationType) -> some View {
Согласен, здесь он лишним получился. Удалил.

2023-12-14 16:43 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Tabbar/Dating/Report&Block/ComplainView.swift
> +                if !textFieldIsFocused {
На макете кнопка не дизейблится. При фокусе она не отображается. Это здесь и реализовано.
В дальнейшем если будут вопросы по поведению кнопки, обязательно исправлю!

2023-12-14 18:41 UTC, baranov89 approved these changes

2023-12-25 13:15 UTC, VolkovsaVSA approved these changes

2023-12-25 18:55 UTC, merged