IOS-15 UI экран Login
openworld-community/Datify-iOS-Core pull request #4
Opened 2023-08-30 15:41 UTC by Irek87

Для демонстрации входа в приложение захардкожены логин и пароль (login: a, password: a).
Кастомный активити индикатор вызывается на 2 секунды для имитации загрузки данных.

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtLogoView.swift
> +            Image("logoImage")
При нажатии на глазик скачет размер всего текстфилда. Возможно надо добавить .scaleToFiT(), но скорее всего надо ограничить высоту фрейма тексфилда жёстко.

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtSecureFieldView.swift
> +                lineWidth: 0.33
А надо ли ставить толщину меньше 1, если айос всё равно минимум 1 пойнт показывает? Я не уверен, но похоже 1 достаточно или прям сильно толсто?

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +            .frame(width: 56, height: 56)
Можно сделать входящий параметр с дефектным значением. Явно нам понадобятся наши спикеры с разными размерами для разных ситуаций =)

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +//            .shadow(radius: 3)
удалить наверное :)

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
Здесь лучше сделать Стейт параметр  во вьюмоделе, например:

```
private enum LoginState {
    case idle, inProcess, success, error
}

final class LoginViewModel {
    @Published var loginState: LoginState = .idle
}
```

и в боди вьюки функцию 


```
var body: some View {
    checkState()
}

@ViewBuilder
private func checkState() -> some View {
    switch viewModel.loginState {
    }
}
```

И просто менять Стейт в нужных местах и ситуациях.

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +    @State var isAnimating = false
В целом рекомендация необязательная, но интересная: есть где-то доклад, не помню где, где чувак говорит, что при объявлении переменных с заранее заданным типом, компиляция у них на проекте выросла на 20%
например:  let qqq: String = .init()

Предлагаю всегда указывать тип. Инициализировать пустые типы через штатный инициализатор .init() =) Нам немного кода, но зато и сразу видно типы, особенно в мешанине Int, Float, CGFloat, Doublt etc.

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            TempView()
На заглуши надо переходить по навигации ))

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            TempView()
На заглуши надо переходить по навигации ))

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
не понял зачем здесь это. понятно что временно, но всё же, когда мы приходим на экран, зачем спине выключать? Видимо его надо выключать, когда уходим, но это не принципиально =)

Ну плюс у нас конкуренси, давайте в тасках с async/await делать и GCD  не использовать, где это возможно =)

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                        Text("Забыли пароль?")
англ

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                //            .disabled(viewModel.isButtonDisabled)
удалить

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +// TODO заменить на кастомный TextFieldView из задачи IOS-1
TODO:
тогда выделение будет тудушки )
комменты тоже на английском оставляем :)

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +struct DtTextFieldView: View {
По сути это первое состояние скьюртексфилда. Сделай входящий параметр в секюрфилд в виде энума: .standart или .secure и показывай/возвращай соответствующий как с кнопками я сделал

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtSecureFieldView.swift
> +    var title: String
`let placeholder `скорее :)

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    var isNotEmpty: Bool {
private

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                .resizable()
почти всегда надо выставлять выравнивание .scaleToFit() .scaleToFill() при ресайзе картинки/иконки. Предлагаю сделать кастомные модификаторы, например:
 1. resizableFit(), где будут   .resizable().scaleToFit()
 2. resizableFill(), где будут   .resizable().scaleToFill()
 
 чтобы не писать их парно постоянно :)

2023-08-30 17:42 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginViewModel.swift
> +    //    func anotherWayToLogIn() {}
удалить

2023-08-30 18:09 UTC, VolkovsaVSA requested changes

2023-08-30 18:11 UTC, VolkovsaVSA requested changes

2023-08-30 18:11 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
>      init(transferData: String) {
transferData: String я добавил лишь для примера, как можно прикидывать данные )) - можно удалить

2023-08-31 05:11 UTC, moraWoo approved these changes

2023-08-31 05:24 UTC, moraWoo commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
У меня вопрос. А возможно ли чтобы шрифты подстраивались под размер экрана или так не делают в проде? Или они всегда будут того же размера как задал дизайнер?

2023-09-02 11:14 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    @Environment(\.dismiss) var dismiss
Done!

2023-09-02 11:16 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSecureFieldView.swift
> +                lineWidth: 0.33
Поставил 1

2023-09-02 11:24 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +            .frame(width: 56, height: 56)
Установил входящий параметр размера. Верно понял, что о размере речь?

2023-09-02 11:24 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +//            .shadow(radius: 3)
Удалил

2023-09-02 11:28 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
@moraWoo как я понимаю apple accessibility, мы устанавливаем системный размер языка, который в зависимости от настроек системы меняется. Люди с проблемами со зрением увеличивают, например.

2023-09-02 11:33 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +    @State var isAnimating = false
Принято! Исправлено

2023-09-02 11:37 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    Text("Добро пожаловать!")
Done!

2023-09-02 11:38 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                        title: "Телефон или почта"
Done

2023-09-02 11:38 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                        title: "Пароль"
Done

2023-09-02 11:39 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                        Text("Забыли пароль?")
Done

2023-09-02 11:40 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    title: "Войти",
Done

2023-09-02 11:41 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    Text("Пожалуйста, введите свои данные для авторизации в приложении")
Done

2023-09-02 11:41 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                //            .disabled(viewModel.isButtonDisabled)
Done

2023-09-02 11:42 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                        //                        viewModel.anotherWayToLogIn()
Done

2023-09-02 11:44 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +// TODO заменить на кастомный TextFieldView из задачи IOS-1
Принято! Исправлено

2023-09-02 11:46 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    var title: String
Исправлено!

2023-09-02 11:47 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSecureFieldView.swift
> +    var title: String
Исправлено!

2023-09-02 11:48 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    var isNotEmpty: Bool {
Исправлено!

2023-09-02 11:49 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginViewModel.swift
> +    //    func anotherWayToLogIn() {}
Done!

2023-09-02 12:01 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                DtButton(
Тут вопрос.
Согласно дизайну у нас кастомное отображение кнопки в состоянии disabled.
Я тут пока задал "серое" отображение в качестве disabled "вручную". 
По-хорошему, нужно кастомизировать модификатор disabled?

2023-09-02 19:10 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
>      init(transferData: String) {
Done!

2023-09-02 19:26 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtLogoView.swift
> +            Image("logoImage")
Избавился от проблемы, сделав через кнопку и зафиксировав её размер.

2023-09-03 11:42 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
@VolkovsaVSA сделал! Но уперся в проблему с показом алерта, т.к. при case .error я должен возвращать какую-то вьюху, поэтому приходится показать пустой текст как вью, уже на которой будет показан алерт. Есть ли вариант показать алерт без доп вью? Не удалось нагуглить.

2023-09-03 11:45 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            TempView()
Вот здесь я поплыл. Что значит по навигации? Мы же так и делаем? При определенных условиях вместо набора полей для ввода данных показываем из NavigationStack заглушку - это не навигация?

2023-09-03 11:46 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
Это ещё придётся доосвоить.

2023-09-03 11:54 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                                viewModel.forgotPassword()
Done!

2023-09-03 13:55 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +struct DtTextFieldView: View {
Done!
Но кажется можно сделать один общий кастомный текстфилд, который в зависимости от параметров будет превращаться в обычный либо в секьюрфилд.

2023-09-03 13:58 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                .resizable()
Теперь у меня Image в текстфилд и секьюрфилд без модификатора resizable(), так как лежит в кнопке.

2023-09-03 14:07 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    DtSecureFieldView(
Done!

2023-09-03 14:40 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    DtTextFieldView(
Done!

2023-09-03 16:37 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +            .frame(width: 56, height: 56)
Да, всё верно, но наверное название просто size

2023-09-03 16:40 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
> У меня вопрос. А возможно ли чтобы шрифты подстраивались под размер экрана или так не делают в проде? Или они всегда будут того же размера как задал дизайнер?

так не делают. Размер шрифта фиксированный и при увеличении экрана должно больше контент вмещаться, а не шрифт увеличиваться. :)

2023-09-03 16:53 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
> @VolkovsaVSA сделал! Но уперся в проблему с показом алерта, т.к. при case .error я должен возвращать какую-то вьюху, поэтому приходится показать пустой текст как вью, уже на которой будет показан алерт. Есть ли вариант показать алерт без доп вью? Не удалось нагуглить.

Тут пока не важно, тк у нас нет концепции обработки ошибок.
Пока можно сделать так:
в функции checkState() в свиче оставить только кейсы error и default 
```
switch viewModel.loginState {
    case .inProcess:
        DtSpinnerView(sideSize: 56)
            .navigationBarBackButtonHidden()
    default: 
        idleView
}
```
В idleView спрятать основное вью
```
private var idleView: some View {
    ...
}
```

В энум добавить функцию проверки состояния ошибки и на основе её показывать алерт. Алерт прикрепить к idleView
```
enum LoginState {
    case idle, inProcess, success, error

    func isError() -> Bool { self == .error }
}
```

```
switch viewModel.loginState {
    case .inProcess:
        DtSpinnerView(sideSize: 56)
            .navigationBarBackButtonHidden()
    default: 
        idleView
            .alert("Wrong Login or password. Please try again!", isPresented: $viewModel.loginState.isError()) {
                Button("OK", action: { viewModel.loginState = .idle })
            }
}
```

2023-09-03 17:15 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            TempView()
Не, сейчас у тебя по навигации идёт переход в логин вью. Потом внутри него идёт подсовывание разных вьюшек в зависимости от скейта. Чтобы перейти по навигации, надо в роутер сделать .push, чтобы по навигейшену перейти на следующие вью.
Посмотри ка я делал, если что, спрашивай. Вот в целом вот алгоритм:
1. Идёшь в папку `NavigationViewBuilder` там все необходимые файлы.
2. В энум `AppRoute` добавляешь нужный кейс нового экрана, например `tabbarView`
3. Вьюшки по навигации создаются в классе `NavigationViewBuilder`. Чтобы там потом не образовалось большой кучи, то можно разделять на флоу. Я это сделал через протоколы. Получается создаёшь нужный протокол для флоу (например регистрация, там несколько шагов как раз) и добавляешь функции создания вьюшек. 
Тут у нас похоже, что табор - это всё же финальный экран флоу логина, поэтому идём в `protocol LoginFlow`
добавляем функцию `createTabbarView()` и внутрь пока ставим временную вьюшку. Так мы через протокол и его реализацию через экстенш просто разделили функции, чтобы они не лежали в одной куче в классе `NavigationViewBuilder`
4. В базовой вью `MainAppView` в функции `buildViews` добавляешь свой кейс.
4. Далее, чтобы совершить переход по навигации, тебе во вьюмодели понадобится наш роутер `Router<AppRoute>`. Поскольку он у нас уже есть в `NavigationViewBuilder`, то ты его просто пропихиваешь в функцию создания логин вью и потом в инициализатор логинВью, а от туда во вью модель.
5. Потом просто дёргаешь нужный метод у роутера viewModel.router.push(.tabbar)

PS: при использовании навигейшен стека, весь стек навигации хранится в простом массиве любых хэшебл элементов (у нас это `@Published var paths: [T]` внутри роутера). Поэтому очень удобно оптом у роутера, например переходить назад - просто выбираем нужный энум .pop(.welcome) и если есть такая вьшка в иерархии навигации, то совершиться переход, если нет, то ничего =) Короче посмотри, вроде в целом всё просто, могу только смущать протоколы для флоу, но опять повторюсь - это только для разделения функция, чтобы всё в куче не лежало. А сама логика навигации внутри роутера, а там пара, строк =) Вьюшки по факту создаются в корневом вью в  `MainAppView`, просто мы их вынесли в класс `NavigationViewBuilder`

2023-09-03 17:29 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
бекграунд поток
```
Task {
    try await Task.sleep(for: .seconds(2))
    someFunction()
}
```
главный поток
```
Task { @MainActor in
    try await Task.sleep(for: .seconds(2))
    someFunction()
}
```
или функцию пометить как мейнактор, то только она будет выполняться в главном потоке
```
@MainActor
func someFunction() {}
```

2023-09-03 17:40 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                DtButton(
хм. мне казалось у нас есть отдельно серая кнопка. А про дизейбл смысл, чтобы кнопка не наживалась, пока данные не введены

2023-09-03 17:57 UTC, VolkovsaVSA requested changes

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Helpers/AppConstants.swift
> +        static let logoSideSize: CGFloat = 24
а вот этот тут не нужно, тк это размер одной конкретной вью.

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtLogoView.swift
> +                    height: AppConstants.Visual.logoSideSize
размер фрейма в этом случае надо передавать через инит, иначе нарушение D в солиде ))) Но а тут в конкретном случае это не нужно, ведь у нас фиксированное вью. Мы же не меняем шрифт при изменении размеров картинки (если бы мы меняли). Короче просто оставь фиксированный размер внутри вью и всё

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtLogoView.swift
> +            Text("Datify")
Тут стринги надо вынести в константу только для того, чтобы она потом нам не выгружалась в файл перевода, тк название не будем же переводить

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +    let sideSize: CGFloat
size

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    @State private var showErrorAlert: Bool = false
можно убрать и пользоваться функцией энума isError из прошлых ответов =)

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            // Временный(?) алерт
комменты тоже на англ =)

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            VStack {
вынести в idleView

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                        Text("Forgot your password?")
Тут лучше использовать кнопку, чтобы видно было нажатие на элемент.

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                Text("Choose another way")
Кнопка, вместо текста

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    let submitlabel: SubmitLabel
значение по-умолчанию .done

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    let imageName: String
сюда лучше сразу Image передавать, тк мы можем использовать и свой имеет и системные имиджи...

2023-09-03 17:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginViewModel.swift
> +    @Published var isShowingSheet = false
название лучше конкретное делать: forgotSheet

2023-09-04 07:08 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +            .frame(width: 56, height: 56)
Done!

2023-09-04 07:47 UTC, Irek87 commented on Datify-iOS-Core/Helpers/AppConstants.swift
> +        static let logoSideSize: CGFloat = 24
Убрал!

2023-09-04 07:48 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtLogoView.swift
> +                    height: AppConstants.Visual.logoSideSize
Done!

2023-09-04 07:50 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtLogoView.swift
> +            Text("Datify")
Исправлено!

2023-09-04 07:51 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSpinnerView.swift
> +    let sideSize: CGFloat
Done!

2023-09-04 07:52 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            // Временный(?) алерт
Corrected!

2023-09-04 07:57 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                        Text("Forgot your password?")
Done!

2023-09-04 07:59 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                Text("Choose another way")
Done!

2023-09-04 08:08 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    let submitlabel: SubmitLabel
Done!

2023-09-04 08:13 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    let imageName: String
Done!

2023-09-04 08:16 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginViewModel.swift
> +    @Published var isShowingSheet = false
Corrected!

2023-09-04 08:27 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
Спасибо! Будем пользоваться! :)

2023-09-04 08:30 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
Так работает имитация запроса в сеть - 

в LoginViewModel:

func authenticate() {
        Task { @MainActor in
            loginState = .inProcess
            
            try await Task.sleep(for: .seconds(2))

            guard email.lowercased() == "a", password == "a" else {
                loginState = .error
                return
            }
            self.loginState = .success

            email = .init()
            password = .init()
        }
    }


P.S. но оставлять так уже не буду

2023-09-04 09:14 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
.alert("Wrong Login or password. Please try again!", isPresented: $viewModel.loginState.isError()) ...

Не работает с $viewModel.loginState.isError(). 
Пришлось использовать дополнительное Bool свойство в LoginViewModel - @Published var isError: Bool, за которым и будем следить для отображения алерта.

2023-09-04 10:28 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            TempView()
Спасибо за подробное объяснение!
Я пытался прокидывать роутер, но у меня возникли проблемы, поэтому подумал, что неверно понял фразу "через навигацию"!
Проблема в прокидывании роутера в ViewModel - при инициализации LoginView мы сразу создаем экземпляр ViewModel, инициализатор которого в свою очередь тоже требует роутер. Чтобы решить этот момент, роутер в ViewModel я делаю опциональным.
Следующий нюанс - когда в LoginView мы перебираем кейсы и видим .success, то по идее тут я должен дергать метод .push(.tabbar), но XCode ругается, что я не возвращаю ему вью. Поэтому дергаю этот метод в ViewModel в функции authenticate(). Но кажется, что это не совсем правильный вариант. Да и теперь по кнопке клавиатуры "done" виснет приложение почему-то. 
@VolkovsaVSA помоги, пожалуйста, разобраться!

2023-09-04 10:29 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                DtButton(
Как в итоге поступаем? Просто дизейблим? Но тогда цвет в состоянии дизейбл не тот, что на дизайне.

2023-09-04 10:30 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    @State private var showErrorAlert: Bool = false
Убрал

2023-09-04 10:30 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            VStack {
Done!

2023-09-04 10:31 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
Пойдет ли так?

2023-09-05 15:32 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +        if viewModel.authenticated && viewModel.showSpinner {
ну пусть пока так

2023-09-05 15:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            TempView()
Посколько вьюмодель создаётся внутри инициализатор вью, достаточно роутер прокинуть в инициализатор вью

2023-09-05 15:40 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +            TempView()
> Посколько вьюмодель создаётся внутри инициализатор вью, достаточно роутер прокинуть в инициализатор вью

всё правильно.
в данном случае нужно только наблюдать что Стейт в рейсе `inProcess`, например, чтобы показать спинер, в остальных случаях (default) логинвью. Вся логика навигации во вьюмодели - всё правильно

2023-09-05 15:41 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                DtButton(
просто дизейбл пока

2023-09-06 12:36 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                DtButton(
Done!

2023-09-07 05:19 UTC, VolkovsaVSA approved these changes

2023-09-07 05:19 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    placeholder: "Phone number or Email",
Ты забыл здесь обернуть в String(localized: ) тк здесь стринга не внутри штатного дай элемента, а передана ф функцию (инициализатор). В таких случаях надо оборачивать

2023-09-07 05:19 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    placeholder: "Password"
Ты забыл здесь обернуть в String(localized: ) тк здесь стринга не внутри штатного дай элемента, а передана ф функцию (инициализатор). В таких случаях надо оборачивать

2023-09-07 05:19 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                title: "Log in",
Ты забыл здесь обернуть в String(localized: ) тк здесь стринга не внутри штатного дай элемента, а передана ф функцию (инициализатор). В таких случаях надо оборачивать

2023-09-07 05:19 UTC, VolkovsaVSA commented
Апрувнул с Небольшим замечанием

2023-09-07 05:34 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    placeholder: "Phone number or Email",
Corrected!

2023-09-07 05:35 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                    placeholder: "Password"
Corrected!

2023-09-07 05:36 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                title: "Log in",
Corrected!

2023-09-07 05:55 UTC, VolkovsaVSA approved these changes

2023-09-07 09:43 UTC, moraWoo approved these changes

2023-09-07 11:22 UTC, merged