Ios 3 UI welcome view
openworld-community/Datify-iOS-Core pull request #6
Opened 2023-09-02 10:31 UTC by c-revolt

2023-09-02 11:20 UTC, c-revolt commented
У меня там вылезла ошибка при тестировании на симуляторе, при переходе на другой экран.

_Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates._

В итоге я так и не понял куда точно вставлять DispatchQueue.main и вставил только в самую нижнюю кнопку экрана, когда и ошибка перестала выпадать вообще везде в других кнопках. Но одним место чую, что это не самое лучшее решение)

Почитал бы ваши замечания, чтобы разобраться в этом моменте)

2023-09-03 15:23 UTC, Irek87 requested changes

2023-09-03 15:23 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/SignInWithButton.swift
> +    let signInWithApple = "Sign in with Apple"
Была рекомендация от @VolkovsaVSA указывать типы явно. 
let signInWithApple: String = "Sign in with Apple"

2023-09-03 15:23 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/SignInWithButton.swift
> +    let signInWithGoogle = "Sign in with Google"
Тут тоже явно показать тип можно

2023-09-03 15:23 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift
> +        ZStack {
ZStack тут нужен?

2023-09-03 15:23 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift
> +            Image(DtImage.vectorImage)
На разных устройствах vectorImage будет одного и того же размера? Как вариант, может будет иметь смысл линию нарисовать и паддингами зафиксировать положение по отношению к краям и тексту?

2023-09-04 05:48 UTC, c-revolt commented on Datify-iOS-Core/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "filename" : "IOS Icon-3.png",
а в чём различия? что лучше?)

2023-09-04 05:49 UTC, c-revolt commented on Datify-iOS-Core/Views/Common/SignInWithButton.swift
> +    let signInWithApple = "Sign in with Apple"
я тут забыл указать, спасибо, что обратил внимание)

2023-09-04 07:04 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "filename" : "IOS Icon-3.png",
Именно для графических изображений (не для фото) кажется лучше векторные, т.к. они во много раз меньше весят, а качество совсем не теряют при растягивании в большой размер. Плюс меньше телодвижений - закидываешь только одно изображение. Отсюда меньше вероятности ошибиться картинками и уменьшение времени на данные операции :)
Парни могут меня поправить, если где-то не совсем точно описал.

2023-09-04 16:39 UTC, VolkovsaVSA commented on Datify-iOS-Core/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "filename" : "IOS Icon-3.png",
Да, лучше картинки в векторе затаскивать, тк при масштабировании не падает качество, но есть нюанс... ))) Это если их дизайнер в векторе нарисовал. А может просто пнгшку в макет закинуть ))). И получится пнгшка внутри вектора, что смысла не имеет =)

2023-09-04 17:44 UTC, VolkovsaVSA requested changes

2023-09-04 17:44 UTC, VolkovsaVSA commented on Datify-iOS-Core.xcodeproj/project.pbxproj
> +			shellScript = "if which swiftlint >/dev/null; then\n  swiftlint\nelse\n  echo \"warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint\"\nfi\n";
скрипт вернуть лучше =)

2023-09-04 19:19 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "filename" : "IOS Icon-3.png",
@VolkovsaVSA  Это про каждую картинку тогда в "дизайнерской" спрашивать? :)

2023-09-06 06:34 UTC, c-revolt commented on Datify-iOS-Core/Assets.xcassets/AppIcon.appiconset/Contents.json
> +      "filename" : "IOS Icon-3.png",
Так, подождите, а как качество падает если изображения x3 в ассете?
Ну, типа icon@1x.png, icon@2x.png, icon@3x.png

2023-09-06 13:00 UTC, Irek87 approved these changes

2023-09-06 13:00 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/SignInWithButton.swift
> +        Button {
а тут же можно кнопку DtButton взять? Чтобы потом при необходимости стиль кнопок в одном месте поменять и всё.

2023-09-07 05:23 UTC, VolkovsaVSA approved these changes

2023-09-07 05:23 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/SignInWithButton.swift
> +    private let signInWithApple: String = "Sign in with Apple"
Ты забыл здесь обернуть в String(localized: ) тк здесь стринга не внутри штатного юай элемента, а передана ф функцию (инициализатор). В таких случаях надо оборачивать

2023-09-07 05:23 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/SignInWithButton.swift
> +    private let signInWithGoogle: String = "Sign in with Google"
Ты забыл здесь обернуть в String(localized: ) тк здесь стринга не внутри штатного юай элемента, а передана ф функцию (инициализатор). В таких случаях надо оборачивать

2023-09-07 05:23 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift
> +    private let alreadyHaveAnAccountTitle: String = "Already have an account?"
По всем стрингам аналогичное замечание

2023-09-07 05:23 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/WelcomeView.swift
> +            DividerLine()
Дава название сделаем DtDividerLine

2023-09-07 06:51 UTC, merged