Ios 1 UI custom text field
openworld-community/Datify-iOS-Core pull request #7
Opened 2023-09-03 12:39 UTC by moraWoo

2023-09-03 15:58 UTC, Irek87 requested changes

2023-09-03 15:58 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/eyeHide.imageset/Contents.json
> +      "scale" : "1x"
svg - в правом меню можно выбрать в поле scales - single scale. Чтобы без 1х, 2х, 3х обойтись.

2023-09-03 15:58 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/eyeHide.imageset/Contents.json
> +      "scale" : "1x"
И галочку поставить в поле Resizing - Preserve Vector Data

2023-09-03 15:58 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/eyeHide.imageset/eyeHide.svg
Можно использовать Image(systemName: "eye.slash")

2023-09-03 15:58 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/eyeShow.imageset/eyeShow.svg
И тут можно взть Image(systemName: "eye")

2023-09-03 15:58 UTC, Irek87 commented on Datify-iOS-Core/Helpers/AppConstants.swift
> +        static let paddings: CGFloat = 16
Кажется дефолтный паддинг и есть 16, если не ошибаюсь @VolkovsaVSA ? Тогда и не нужно явно указывать или не будет лишним?

2023-09-03 15:58 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/CustomTextField/DtCustomTF.swift
> +extension View {
С расширениями у нас там отдельная папка есть. Возможно это можно вынести туда, если @VolkovsaVSA  посчитает нужным :)

2023-09-03 15:58 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/CustomTextField/PreviewCTF.swift
> +    @State private var inputPhoneEmail = ""
От Сергея была рекомендация:

В целом рекомендация необязательная, но интересная: есть где-то доклад, не помню где, где чувак говорит, что при объявлении переменных с заранее заданным типом, компиляция у них на проекте выросла на 20%
например: let qqq: String = .init()
Предлагаю всегда указывать тип. Инициализировать пустые типы через штатный инициализатор .init() =) Нам немного кода, но зато и сразу видно типы, особенно в мешанине Int, Float, CGFloat, Double etc.

2023-09-04 12:09 UTC, VolkovsaVSA commented on Datify-iOS-Core/Helpers/AppConstants.swift
> +        static let paddings: CGFloat = 16
да, дефолтный 16. Вообще, опять же это всё локальные константы. Нажива из тащить в общие неочень понятно. Вот cornerRadius везде одинаковый, кнопки одинаковые... короче, только то, что выглядит как параметр для многих вью

2023-09-04 16:33 UTC, VolkovsaVSA requested changes

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/DtCustomTF.swift
> +        case text
Наверное name, тк это все же специфический Филд с выравниванием по центру

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/DtCustomTF.swift
> +    enum Style {
Сюда надо брать стрингВелью, сюда же можно убрать в функции все связанные данные:
1. Тип контента филда
2. Тип калвы
3. Кнопка клавы (смотри `SubmitLabel`)
4. Выравнивание

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/PreviewCTF.swift
> +    @State private var inputPhoneEmail = ""
👍

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/PreviewCTF.swift
> +        PreviewCTF(
Отдельный файл для Превью мне кажется слишком. В превью юая же можно несколько вью запихнуть Это всё надо перенести превью соответствующих вьюх с учётом следующих замечаний

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/PreviewCTF.swift
> +    @Binding var inputPhoneEmail: String
для превью можно переменные не создавать, а использовать инициализатор через констант `.constant("123")` смотри далее

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/PreviewCTF.swift
> +            DtCustomTF(
```
ForEach(DtCustomTF.Style.AllCases) { field in
    DtCustomTF()
}
```

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/PreviewCTF.swift
> +                input: $inputPhoneEmail,
вместо `$inputPhoneEmail` можно сделать `.constant("email")` и тогда не нужны переменные в превью

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/Views/RegularTFView.swift
> +    var action: (() -> Void)?
`let action: () -> Void)`

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/Views/RegularTFView.swift
> +    let placeholderColor: Color
не вижу смысла сюда передавать цвет плейсхолдера, тк он везде же один и тот же

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/Views/RegularTFView.swift
> +        .dtTypo(.p2Regular, color: input.isEmpty ? placeholderColor : Color.textPrimary)
так цвет плейсхолдера не меняется :)

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/Views/RegularTFView.swift
> +        .padding(.horizontal, AppConstants.Visual.paddings)
паддинг не надо выносить куда-то

2023-09-04 16:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/Views/RegularTFView.swift
> +        }
строки 36 по 50 такие же как и в SecureTextFieldView. Поэтому надо вынести в свой кодификатор, чтобы не копипастить код. Плюс надо добавить `.disableAutocorrection(true)`

2023-09-09 09:09 UTC, moraWoo commented on Datify-iOS-Core/Assets.xcassets/eyeHide.imageset/eyeHide.svg
Он не очень похож на figma. Поэтому я брал кастомную картинку
![image](https://github.com/openworld-community/Datify-iOS-Core/assets/101454100/674fad59-f2ad-471a-b536-28e73e936e1e)

2023-09-09 09:09 UTC, moraWoo commented on Datify-iOS-Core/Assets.xcassets/eyeHide.imageset/Contents.json
> +      "scale" : "1x"
done

2023-09-09 09:10 UTC, moraWoo commented on Datify-iOS-Core/Assets.xcassets/eyeShow.imageset/eyeShow.svg
Предыдущий ответ

2023-09-09 10:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Assets.xcassets/eyeHide.imageset/eyeHide.svg
Согласен с Ильдаром: иконки все надо брать из фирмы, даже если есть такие же системные

2023-09-09 10:58 UTC, VolkovsaVSA commented on Datify-iOS-Core/Assets.xcassets/eyeShow.imageset/eyeShow.svg
> И тут можно взть Image(systemName: "eye")

не нужно :) Надо все иконки тянуть из фигмы - возьмите это как правило.

2023-09-09 11:00 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/eyeShow.imageset/eyeShow.svg
Ок!
Формат любой тянуть или какой поменьше весит?

2023-09-09 11:33 UTC, VolkovsaVSA commented on Datify-iOS-Core/Assets.xcassets/eyeShow.imageset/eyeShow.svg
> Ок!
> Формат любой тянуть или какой поменьше весит?

А там свгшки много весят? По возможности свгшки

2023-09-09 12:11 UTC, moraWoo commented on Datify-iOS-Core/Views/Common/CustomTextField/DtCustomTF.swift
> +        case text
Есть name, но есть и другие вроде. Поэтому сделал общий для всех таких же. 
![image](https://github.com/openworld-community/Datify-iOS-Core/assets/101454100/0d67ac4e-027d-47d0-a883-3cba13b20780)

2023-09-09 12:12 UTC, moraWoo commented on Datify-iOS-Core/Views/Common/CustomTextField/Views/RegularTFView.swift
> +    var action: (() -> Void)?
Тут есть сомнения по моему новому решению, правильно ли я тебя понял

2023-09-09 14:57 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/Views/RegularTFView.swift
> +    var action: (() -> Void)?
клоужер можно сделать  let
экшен, наверное, всегда будет (убрать опциона), тк мы всегда должны что-то делать по нажатию на кнопку ввода.

2023-09-11 06:10 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Common/CustomTextField/DtCustomTF.swift
> +        case text
Тогда надо передавать выравнивание, чтобы можно было настраивать это поле, можно через ассоциативный параметр энума.

2023-09-11 07:05 UTC, VolkovsaVSA approved these changes

2023-09-11 07:25 UTC, Irek87 approved these changes

2023-09-11 13:02 UTC, VolkovsaVSA approved these changes

2023-09-11 16:14 UTC, merged