IOS-9 UI registration email input screen
openworld-community/Datify-iOS-Core pull request #8
Opened 2023-09-08 07:32 UTC by Irek87

В данный момент для ознакомления на экран ввода email можно перейти по кнопке "Sign up" с WelcomeView.

2023-09-09 07:46 UTC, VolkovsaVSA requested changes

2023-09-09 07:46 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailView.swift
> +         viewModel: RegEmailViewModel = RegEmailViewModel(router: nil)
вот здесь я не понял зачем это (передача вьюмодели этой вьюги снаружи)? :)
Предлагаю, как я в примерах делал, в инит вьюхи передавать необходимые только параметры. Вьюмодель формировать внутри инита, тк она нужна только для этой вьюхи. Поправь на экране логина тоже, я видимо не заметил.
Если вдруг надо будет много параметров, то прокинем вьюмодель родителя целиком при необходимости.

2023-09-09 07:46 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailView.swift
> +    private unowned let router: Router<AppRoute>
роутер во вью не нужен же, если он внутри вьюмодели

2023-09-09 07:46 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    let image: Image?
Я понял, что ты временно это сделал, чтобы создавать тф без доп иконки. Тогда пока предлагаю сделать имедж и экшен в опциональный тюпл, тк они всегда парой идут
let additionalFunction: (image: Image, action: ()->Void)?  В ините сделать параметр по-умолчанию = nil.
Да и ещё экшен для кнопки клавы есть же отдельный, который .onSubmit - его тоже нужно в ты передавать, чтобы каждый раз не писать этот модификатор :)

2023-09-09 07:46 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailView.swift
> +            String(localized: "Wrong format of email address. Please try again!"),
В алёрт вроде можно так передавать без оборачивайся - он же штатный элемент )

2023-09-09 07:46 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailView.swift
> +        .onTapGesture {
Можно вынести в модификатор, чтобы потом применять у головному элементу внутри вью

```
extension View {
    func hideKeyboardTapOutside() -> some View {
        onTapGesture { UIApplication.shared.dismissKeyboard() }
    }
}
```
```
var body: some View {
   mainView()
       .hideKeyboardTapOutside()
}
```

2023-09-09 07:46 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailViewModel.swift
> +    weak var router: Router<AppRoute>?
Не вижу тут необходимости в опциональном роутер и weak соответсвенно, тк роутер не ссылается на вьюмодели, плюс существует весь цикл жизни приложения. 
Достаточно `unowned let router: Router<AppRoute>`

Хотя если есть другие соображения, излагай :)

2023-09-09 07:46 UTC, VolkovsaVSA commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailViewModel.swift
> +        REGEX = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
тут тоже не понял зачем 2 строчки, почему не `let REGEX: String = ...`?

2023-09-09 18:46 UTC, moraWoo commented on Datify-iOS-Core/Assets.xcassets/.DS_Store
У тебя есть .gitignore? Надо добавить .DS_Store в gitignore, чтобы он не коммитился вместе с кодом. У меня глобальный лежит в папке /Users/ildarkhabibullin/ и не нужно в каждом проекте создавать отдельный. Сюда не прикладывается, но я могу в телеге скинуть если нужно.

2023-09-09 18:46 UTC, moraWoo commented on Datify-iOS-Core/Extensions/UIApplication+extension.swift
У меня такой же создан файл. У меня название просто неправильное. Твой оставь, я свой удалю

2023-09-09 19:26 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/.DS_Store
Спасибо, что указал!

2023-09-09 19:27 UTC, Irek87 commented on Datify-iOS-Core/Extensions/UIApplication+extension.swift
Ок!

2023-09-10 11:06 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailView.swift
> +         viewModel: RegEmailViewModel = RegEmailViewModel(router: nil)
Понял! Исправил!

2023-09-10 11:08 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailView.swift
> +    private unowned let router: Router<AppRoute>
Убрал! В LoginView тоже.

2023-09-10 11:10 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailView.swift
> +            String(localized: "Wrong format of email address. Please try again!"),
Исправлено!

2023-09-10 11:14 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailViewModel.swift
> +    weak var router: Router<AppRoute>?
Да, тут я запутался.
Исправил!

2023-09-10 11:15 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailViewModel.swift
> +        REGEX = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
Исправлено!

2023-09-10 19:01 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +    let image: Image?
Оба момента поправил.

2023-09-10 19:14 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/RegEmailView.swift
> +        .onTapGesture {
Done!

2023-09-11 06:25 UTC, VolkovsaVSA requested changes

2023-09-11 06:25 UTC, VolkovsaVSA commented on Datify-iOS-Core/.DS_Store
Удалить

2023-09-11 06:25 UTC, VolkovsaVSA commented on Datify-iOS-Core/Assets.xcassets/.DS_Store
Удалить

2023-09-11 08:34 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSecureFieldView.swift
> +                    image: Image(systemName: "eye"),
Даже для временного решения?

2023-09-11 08:37 UTC, Irek87 commented on Datify-iOS-Core/Views/Common/DtSecureFieldView.swift
> +                    image: Image(systemName: "eye"),
Done!

2023-09-11 09:15 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
> +                        image: Image(systemName: "xmark"),
Done!

2023-09-11 09:20 UTC, Irek87 commented on Datify-iOS-Core/Views/Main/Welcome/Login/LoginView.swift
>          text != ""
Согласен! Добавил!

2023-09-11 09:20 UTC, Irek87 commented on Datify-iOS-Core/Assets.xcassets/.DS_Store
Done!

2023-09-11 09:20 UTC, Irek87 commented on Datify-iOS-Core/.DS_Store
Done!

2023-09-11 10:57 UTC, VolkovsaVSA approved these changes

2023-09-12 19:12 UTC, goodrgn approved these changes

2023-09-12 19:37 UTC, merged